### ISSUE TITLE
Regression: 'LazyType' object has no attribute 'CONNECTION_CLASS'

### ISSUE THREAD

**Issue by devkral** [blb-ventures/strawberry-django-plus#116]
After the upgrade to 1.26 I get the issue:

  File "xxx/.venv/lib/python3.10/site-packages/strawberry_django_plus/relay.py", line 952, in `__call__`
    ntype.CONNECTION_CLASS[ntype],
AttributeError: 'LazyType' object has no attribute 'CONNECTION_CLASS'

In my code I use the LazyType type manually (strawberry.LazyType), so I think you miss a check or default attribute
